class Except2{
    public static void func2(){
	try{
	    System.out.println("G");
	}
	catch(Exception e){
	   
	}
	finally{
	    System.out.println("A");
	}
    }
}
